DROP TABLE IF EXISTS paste_folders CASCADE;
DROP TABLE IF EXISTS folders CASCADE;
DROP TABLE IF EXISTS paste_tags CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS pastes CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;