DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS proposal_comments CASCADE;
DROP TABLE IF EXISTS paste_proposals CASCADE;
DROP TABLE IF EXISTS paste_views CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS comments CASCADE;